/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import pecl1.ClienteT;
import pecl1.CocineroT;
import pecl1.EmpleadoT;
import pecl1.Mesa;
import pecl1.Mostrador;
import distribuido.Cliente;
import distribuido.Servidor;
import distribuido.RestauranteDist;


/**
 *
 * @author Fran
 */
public class RestauranteSwing extends javax.swing.JFrame {

    /**
     * Creates new form RestauranteSwing
     */
    
    private Mostrador mo;
    private Mesa me;
    private EmpleadoT emp1,emp2;
    private CocineroT coc1, coc2, coc3;
    private ArrayList <javax.swing.JTextField> mensajes;
    private Servidor enviarDatos;
   
    
    
    public RestauranteSwing() throws InterruptedException {
        initComponents();
        setVisible(true);
        
        //Inicializamos un array de string donde se guardan los mensajes
        //que se pasaran mediante sockets
        mensajes = new ArrayList<>();
        mensajes.add(mostradortxt);
        mensajes.add(mesatxt);
        
        //Creamos un objeto de tipo servidor que tiene como parametro los
        //mensajes que queremos pasar, e iniciamos el hilo
        
        Servidor s = new Servidor(mensajes);
        s.start();
        
        //Creamos e inicializamos el mostrador y la mesa
        //Creamos el cliente y un arraylist de clientes donde se iran
        //introduciendo despues de crearse
        Mostrador most = new Mostrador(10, mostradortxt);
        Mesa mesa = new Mesa(20, mesatxt);
        ClienteT c;
        ArrayList<ClienteT> clientes = new ArrayList<ClienteT>();

        //Con este bucle creamos los 200 clientes, los añadimos
        //al arraylist de clientes e iniciamos los hilos
        
        for (int i=0; i<200; i++){
             c = new ClienteT("Cliente"+i, most);
             clientes.add(c);
             c.start();
        }
        
        //Creamos e inicializamos los 2 empleados y los 3 cocineros
        
        emp1 = new EmpleadoT("Empleado1", most, mesa, empleado1txt);
        emp2 = new EmpleadoT("Empleado2", most, mesa, empleado2txt);
        coc1 = new CocineroT("Cocinero1", mesa, cocinero1txt);
        coc2 = new CocineroT("Cocinero2", mesa, cocinero2txt);
        coc3 = new CocineroT("Cocinero3", mesa, cocinero3txt);
        
        //Iniciamos sus respectivos hilos
        emp1.start();
        emp2.start();       
        coc1.start();       
        coc2.start();      
        coc3.start();
        
        //Recorremos el array de clientes para indicarles
        //que esperen a que se termine la ejecucion
        
        for(int j=0; j<clientes.size(); j++){
            
            clientes.get(j).join();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mostradortxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empleado1txt = new javax.swing.JTextField();
        empleado2txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mesatxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cocinero1txt = new javax.swing.JTextField();
        cocinero2txt = new javax.swing.JTextField();
        cocinero3txt = new javax.swing.JTextField();
        pausar = new javax.swing.JButton();
        pausarEmp1 = new javax.swing.JButton();
        pausarEmp2 = new javax.swing.JButton();
        reanudarEmp1 = new javax.swing.JButton();
        reanudarEmp2 = new javax.swing.JButton();
        reanudarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Contenido del mostrador de pedidos:");

        mostradortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostradortxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Empleado 1:");

        jLabel3.setText("Empleado 2:");

        empleado1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado1txtActionPerformed(evt);
            }
        });

        empleado2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleado2txtActionPerformed(evt);
            }
        });

        jLabel4.setText("Contenido de la mesa de platos:");

        mesatxt.setToolTipText("");
        mesatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesatxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Cocinero 1:");

        jLabel6.setText("Cocinero 2 ");

        jLabel7.setText("Cocinero 3:");

        cocinero1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocinero1txtActionPerformed(evt);
            }
        });

        cocinero2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocinero2txtActionPerformed(evt);
            }
        });

        pausar.setText("Pausar todo");
        pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarActionPerformed(evt);
            }
        });

        pausarEmp1.setText("Pausar empleado 1");
        pausarEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarEmp1ActionPerformed(evt);
            }
        });

        pausarEmp2.setText("Pausar empleado 2");
        pausarEmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarEmp2ActionPerformed(evt);
            }
        });

        reanudarEmp1.setText("Reanudar empleado 1");
        reanudarEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudarEmp1ActionPerformed(evt);
            }
        });

        reanudarEmp2.setText("Reanudar empleado 2");
        reanudarEmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudarEmp2ActionPerformed(evt);
            }
        });

        reanudarTodo.setText("Reanudar todo");
        reanudarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cocinero1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cocinero2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(123, 123, 123)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cocinero3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(reanudarEmp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pausarEmp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pausarEmp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(reanudarEmp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mostradortxt)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(empleado1txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(132, 132, 132)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(empleado2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(mesatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pausar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reanudarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostradortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleado1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empleado2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cocinero1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cocinero2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cocinero3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pausar)
                    .addComponent(pausarEmp1)
                    .addComponent(pausarEmp2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reanudarEmp1)
                    .addComponent(reanudarEmp2)
                    .addComponent(reanudarTodo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void mesatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesatxtActionPerformed

    private void pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarActionPerformed
        // TODO add your handling code here:

        //Llamamos al metodo pausarHilo para empleados y cocineros
        //para conseguir que se pare el programa
        emp1.pausarHilo();
        emp2.pausarHilo();
        coc1.pausarHilo();
        coc2.pausarHilo();
        coc3.pausarHilo();

    }//GEN-LAST:event_pausarActionPerformed

    private void empleado1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado1txtActionPerformed

    private void mostradortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostradortxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mostradortxtActionPerformed

    private void empleado2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleado2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleado2txtActionPerformed

    private void cocinero1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocinero1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cocinero1txtActionPerformed

    private void cocinero2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocinero2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cocinero2txtActionPerformed

    private void pausarEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarEmp1ActionPerformed
        // TODO add your handling code here:
        //Llamamos a pausarHilo para pausar el empleado 1
        emp1.pausarHilo();
        
    }//GEN-LAST:event_pausarEmp1ActionPerformed

    private void pausarEmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarEmp2ActionPerformed
        // TODO add your handling code here:
        //Llamamos a pausarHilo para pausar el empleado 2
        emp2.pausarHilo();
    }//GEN-LAST:event_pausarEmp2ActionPerformed

    private void reanudarEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudarEmp1ActionPerformed
        // TODO add your handling code here:
        //Llamamos a pausarHilo para reanudar el empleado 1
        emp1.reanudarHilo();
    }//GEN-LAST:event_reanudarEmp1ActionPerformed

    private void reanudarEmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudarEmp2ActionPerformed
        // TODO add your handling code here:
        //Llamamos a pausarHilo para reanudar el empleado 2
        emp2.reanudarHilo();
    }//GEN-LAST:event_reanudarEmp2ActionPerformed

    private void reanudarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudarTodoActionPerformed
        // TODO add your handling code here:
        //Llamamos a reanudarHilo para empleados y cocineros
        //para conseguir que se reanude el programa
        emp1.reanudarHilo();
        emp2.reanudarHilo();
        coc1.reanudarHilo();
        coc2.reanudarHilo();
        coc3.reanudarHilo();
    }//GEN-LAST:event_reanudarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestauranteSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RestauranteSwing().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(RestauranteSwing.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cocinero1txt;
    private javax.swing.JTextField cocinero2txt;
    private javax.swing.JTextField cocinero3txt;
    private javax.swing.JTextField empleado1txt;
    private javax.swing.JTextField empleado2txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mesatxt;
    private javax.swing.JTextField mostradortxt;
    private javax.swing.JButton pausar;
    private javax.swing.JButton pausarEmp1;
    private javax.swing.JButton pausarEmp2;
    private javax.swing.JButton reanudarEmp1;
    private javax.swing.JButton reanudarEmp2;
    private javax.swing.JButton reanudarTodo;
    // End of variables declaration//GEN-END:variables
}
